server:
  port: 8001
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://postgres.cfk00ou0if7d.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: vaibhavjadhav
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://15.206.148.78/eureka
logging:
  level:
    org.springframework.security: trace
