server:
  port: 8002
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://postgres.ctkaccukyllh.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Vaibhav123
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://52.66.134.11:8761/eureka
logging:
  level:
    org.springframework.security: trace
