server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.security: trace
jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
