name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "FE/social-app/**"

jobs:
  build-react:
    name: Build and Test React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: FE/social-app

      - name: Build the application
        run: npm run build
        working-directory: FE/social-app

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for React app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/social-app .
        working-directory: FE/social-app

      - name: Push Docker image for React app
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/social-app:latest

  deploy-react:
    name: Deploy React to EC2
    runs-on: aws-ec2
    needs: build-react
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:latest

      - name: Delete old container
        run: docker rm -f reactContainer || true

      - name: Run Docker container
        run: docker run -d -p 5173:80 --name reactContainer ${{ secrets.DOCKER_USERNAME }}/social-app
