name: User Info Service CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "BE/user-info-service/**"

jobs:
  build-user-info-service:
    name: Build and Test User Info Service App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests
        working-directory: BE/user-info-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Spring Boot app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-info-service:latest .
        working-directory: BE/user-info-service

      - name: Push Docker image for Spring Boot app
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-info-service:latest

  deploy-user-info-service:
    name: Deploy UserInfo Service to EC2
    runs-on: aws-ec2-user-info-service
    needs: build-user-info-service
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/user-info-service:latest

      - name: Delete old container
        run: docker rm -f userInfoServiceContainer || true

      - name: Run Docker container
        run: |
          docker run -d -p 8002:8002 --name userInfoServiceContainer \
            -e SPRING_PROFILES_ACTIVE=dev \
            ${{ secrets.DOCKER_USERNAME }}/user-info-service:latest
